apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce-deployment
  labels:
    app: commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commerce
  template:
    metadata:
      labels:
        app: commerce
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows # Run on a Windows Node
      containers:
      - name: commerce
        image: avivasolutionsnl.azurecr.io/mercury-demo-commerce:9.0.3-20190527
        ports:
        - containerPort: 4000
        - containerPort: 4200
        - containerPort: 5000
        - containerPort: 5005
        - containerPort: 5010
        - containerPort: 5015
        - containerPort: 5050
        args:
        - -commerceHostname
        - commerce
        - -sitecoreHostname
        - sitecore
        resources:
          requests:
            cpu: 500m # 50% of 1 vCPU
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: commerce
spec:
  ports:
  - name: port4000
    protocol: TCP
    port: 4000
  - name: port4200
    protocol: TCP
    port: 4200
  - name: port5000
    protocol: TCP
    port: 5000
  - name: port5005
    protocol: TCP
    port: 5005
  - name: port5010
    protocol: TCP
    port: 5010
  - name: port5015
    protocol: TCP
    port: 5015
  - name: port5050
    protocol: TCP
    port: 5050
  selector:
    app: commerce
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: commerce
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: commerce-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Target is 50% of the requested CPU, i.e. 50% of 500 milli CPU in this case
