apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitecore-deployment
  labels:
    app: sitecore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sitecore
  template:
    metadata:
      labels:
        app: sitecore
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows # Run on a Windows Node
      containers:
      - name: sitecore
        image: avivasolutionsnl.azurecr.io/mercury-demo-sitecore:9.0.3-20190527-k8s
        ports:
          - containerPort: 80
        args:
        - -commerceHostname
        - commerce
        volumeMounts:
          - mountPath: "/license"
            name: license
            readOnly: true
      volumes:
        - name: license
          secret:
            secretName: sitecore-license
---
apiVersion: v1
kind: Service
metadata:
  name: sitecore
spec:
  ports:
  - name: port80
    protocol: TCP
    port: 80
  # Commerce engine uses https://sitecore    
  - name: port443
    protocol: TCP
    port: 443
  selector:
    app: sitecore
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sitecore
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
spec:
  tls:
  - hosts:
    - mercury-www.xc9-k8s.rocks
    secretName: tls-secret-www
  rules:
  - host: mercury-www.xc9-k8s.rocks
    http:
      paths:
      - backend:
          serviceName: sitecore
          servicePort: 80
        path: /