apiVersion: apps/v1
kind: Deployment
metadata:
  name: commerce-deployment
  labels:
    app: commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commerce
  template:
    metadata:
      labels:
        app: commerce
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows # Run on a Windows Node
      containers:
      - name: commerce
        image: avivasolutionsnl.azurecr.io/sitecore-xc-commerce:9.1.0-20190910-proxy
        ports:
        - containerPort: 4000
        - containerPort: 4200
        - containerPort: 5000
        - containerPort: 5005
        - containerPort: 5010
        - containerPort: 5015
        args:
        - -commerceHostname
        - commerce.xc9-k8s.rocks
        - -identityHostname
        - identity.xc9-k8s.rocks
        - -sitecoreHostname
        - www.xc9-k8s.rocks
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: commerce
spec:
  ports:
  - name: port4000
    protocol: TCP
    port: 4000
  - name: port4200
    protocol: TCP
    port: 4200
  - name: port5000
    protocol: TCP
    port: 5000
  - name: port5005
    protocol: TCP
    port: 5005
  - name: port5010
    protocol: TCP
    port: 5010
  - name: port5015
    protocol: TCP
    port: 5015
  selector:
    app: commerce
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: commerce
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
spec:
  tls:
  - hosts:
    - bizfx.xc9-k8s.rocks
    - commerce.xc9-k8s.rocks
    - plumber.xc9-k8s.rocks
    secretName: tls-secret-commerce
  rules:
  - host: bizfx.xc9-k8s.rocks
    http:
      paths:
      - backend:
          serviceName: commerce
          servicePort: 4200
        path: /
  - host: commerce.xc9-k8s.rocks
    http:
      paths:
      - backend:
          serviceName: commerce
          servicePort: 5000
        path: /
  - host: plumber.xc9-k8s.rocks
    http:
      paths:
      - backend:
          serviceName: commerce
          servicePort: 4000
        path: /
